FROM node

WORKDIR /usr/src/app

## copy necessary files
ADD ./dist ./dist
ADD ./Mock ./Mock
ADD server.js ./server.js
ADD package.json package.json
ADD settings.json settings.json
ADD ./node_modules ./node_modules

CMD ["npm", "run", "start-opplaering"]

