export interface VeilederBrukerTilknytning {
  veilederIdent: string;
  aktorId: string;
  enhet: string;
}

export const enum veilederBrukerTilknytningActionTypes {
  PUSH_VEILEDERBRUKERTILKNYTNING_PUSHER = 'PUSH_VEILEDERBRUKERTILKNYTNING_PUSHER',
  PUSH_VEILEDERBRUKERTILKNYTNING_PUSHET = 'PUSH_VEILEDERBRUKERTILKNYTNING_PUSHET',
  PUSH_VEILEDERBRUKERTILKNYTNING_FORESPURT = 'PUSH_VEILEDERBRUKERTILKNYTNING_FORESPURT',
  PUSH_VEILEDERBRUKERTILKNYTNING_FEILET = 'PUSH_VEILEDERBRUKERTILKNYTNING_FEILET'
}
