export const CONTEXT_EVENT_TYPE = {
  NY_AKTIV_ENHET: 'NY_AKTIV_ENHET',
};

export const OVERSIKT_VISNING_TYPE = {
    ENHETENS_OVERSIKT: 'ENHETENS_OVERSIKT',
    MIN_OVERSIKT: 'MIN_OVERSIKT',
    VEILEDEROVERSIKT: 'VEILEDEOVERSIKT'
};
